### ISSUE TITLE
Can't join server with this mod installed

### ISSUE THREAD

**Issue by PanoptesDreams** [juancarloscp52/spyglass-improvements#2]
Hi there, I'm building a **Forge** Server and your mod is the only one stumping me now.

Clients can't connect to a server while they (the client) have the mod installed (Some Forge server mod mismatch BS)
The solution would be to add it to the server so that the mod list is given the okay 👌 by the Forge Gods ✨
Alas this:

[main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Spyglass Improvements (spyglass_improvements) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.1-39.0.76.jar%23146!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.76.jar%23146!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.76.jar%23146!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[fmlcore-1.18.1-39.0.76.jar%23146!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:177) ~[fmlcore-1.18.1-39.0.76.jar%23146!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:46) ~[forge-1.18.1-39.0.76-universal.jar%23149!/:?]
	at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23145!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.76.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

So. I disable your mod completely, everything works.
Help?

Spyglass Improvements 1.1 forge
JDK 17
Minecraft 1.18.1
Forge Modloader 39.0.76
Windows 10 x64 21H1 19043.1526
Windows 10 x64 21H2 19044.1526

**Comment by juancarloscp52** [comment]
I've solved the issue, the fix will be included with the next version, until then, you can use this build:

[spyglass_improvements-1.1SERVERFIX+mc1.18.1+forge.zip](https://github.com/juancarloscp52/spyglass-improvements/files/8081839/spyglass_improvements-1.1SERVERFIX%2Bmc1.18.1%2Bforge.zip)

**Comment by PanoptesDreams** [comment]
I find it a little ridiculous that Forge does this whole gatekeeping thing with installed mods. With Fabric this is not an issue, and when I left the Forge community it wasn't this hard either.
It simply reminds me of all the reasons why I left Forge in favor of Fabric.

And after waiting an exorbitant amount of time for the game to launch I can confirm it is working!

Thank you so much!

And I hope to see more of your work in Fabric :)

**Comment by PanoptesDreams** [comment]
This is probably a new/separate issue but imma throw it in here.

New crash caused by adjusting configuration settings in-game

[crash-2022-02-17_16.16.10-client.txt](https://github.com/juancarloscp52/spyglass-improvements/files/8085288/crash-2022-02-17_16.16.10-client.txt)

**Comment by juancarloscp52** [comment]
Ok shoud be fixed now in the latest release, available on curseforge. Thanks for reporting this issue!
